# Permalinks
permalink:        /:categories/:title/

# Setup
url:              http://saiprasanna.in

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Code SAI

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Engineer by day, Hacker by night, Guitarist in between and Philosopher forever.

# The tags listed as entries in the sidebar
sidebar_tags:     []

# Fallback image and color if not overwritten for tag or post
image:            /public/img/cover.png
color:            '#A85641'

author:
  name:           'Sai Prasanna'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        sai_prasanna
  github:         sai-prasanna

  # Setting a disqus username will enable the comment section
  disqus:         saiprasanna

  # This photo will be used in the about section
  photo:          /public/img/author.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    I am software engineer from Chennai. I am deeply passionate about computer science.
    When I am not busy hacking code  (hoping to build skynet) I learn to play the guitar,
    and read books.

timezone: Asia/Calcutta

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
